[build]
  publish = "frontend"
  command = "pip install -r backend/requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/app/upload"
  status = 200

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/app/analyze"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/app/health"
  status = 200

[[redirects]]
  from = "/results"
  to = "/results.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/landing.html"
  status = 200

[functions]
  directory = "backend"
