services:
  - type: web
    name: resumepro
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: UPLOAD_FOLDER
        value: uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
